services:
    bot:
        image: discord-tts-bot:local
        restart: unless-stopped
        volumes:
          - type: bind
            source: ./config.toml
            target: /bot/config.toml

        depends_on: [database, tts-service]
        network_mode: "host"
    database:
        image: postgres:13
        restart: unless-stopped
        ports: [5432:5432]
        environment: 
            POSTGRES_USER: tts
            POSTGRES_PASSWORD: tts_password
    tts-service:
        image: gnomeddev/tts-service
        restart: unless-stopped
        volumes:
          - type: bind
            source: ${GOOGLE_APPLICATION_CREDENTIALS}
            target: /gcp.json
        environment:
          -  IPV6_BLOCK=DISABLE
          -  AWS_EC2_METADATA_DISABLED=true
          -  LOG_LEVEL=INFO
          -  BIND_ADDR=0.0.0.0:20310
          -  GOOGLE_APPLICATION_CREDENTIALS=/gcp.json
        network_mode: "host"
        expose: [20310]
